## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'orsay'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_orsay' #to modify
description = 'PyMoDAQ Orsay STEM and Camera plugin to control Ropers or Princeton Cameras and STEM (Scanning Tunnel Electron Microscope) using the HOUDs2 electronic module '

author = 'SÃ©bastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = []
##